#!/bin/bash

USERID=$(id -u)

VALIDATE(){
    if [ $1 -ne 0 ]
    then
         echo "$2 .... failure"
         exit 1
     else    
         echo "$2 .... success"
      fi
}

if [ $? -ne 0 ]
then
     echo "ERROR: you must have sudo access to run the script"
     exit 1
fi

dnf list installed mysql

if [ $? -ne 0 ]
then
    dnf install mysql -y
    VALIDATE $? "Installing my sql"
    else
         echo "mysql already installed"
fi

dnf list installed git

if [ $? -ne 0 ]
   then
         dnf install git -y
         VALIDATE $? "installig .... git"
   else
        echo "git is already .... Installed"
fi
     

        