#!/bin/bash
USERID=$(id -u)
if [ $USERID -ne 0 ]
then
echo "failure.. need sudo access"
exit 1
fi


dnf list instlled mysql

if [ $? -ne 0 ]
     dnf install mysql -y then

echo "installing mysql...Failure"
exit 1
else
echo "git installing.... success"
else
     echo "mysql already....Installed"
fi