#!/bin/bash
USERID=$(id -u)

if [ $USERID -ne 0 ]
then
echo "failure.. need sudo access"
exit 1
fi


dnf list installed mysql

if [ $? -ne 0 ] then
    ech0 "mysql not found.. installing mysql"
     dnf install mysql -y 

      if [ $? -ne 0 ]
      then
echo "installing mysql...Failure"
exit 1
else
echo "mysql installing.... success"
fi
else
     echo "mysql already....Installed"
fi