#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14}  # if not provided, default is 14 days

LOGS_FOLDER="/var/log/shell-script"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log" # /var/log/shell-script/16-logs.log

mkdir -p $LOGS_FOLDER
echo "Script started executed at: $(date)" | tee -a $LOG_FILE

if [ $USERID -ne 0 ]; then
    echo "ERROR:: Please run this script with root privelege"
    exit 1 # failure is other than 0
fi

USAGE(){
    echo -e "$R USAGE: sudo sh backup.sh <SOURCE.DIR> <DEST.DIR> <DAYS>[optional] , default 14 days] $N"
    exit 1
}

#check SOOURCE_DIR AND DEST_DIR PASSED OR NOT
if [ $# -lt 2 ]; then
   USAGE
fi

#check SOOURCE_DIR AND DEST_DIR exist or not
if [ ! -d $SOURCE_DIR ]; then
   echo -e "$R source $SOURCE_DIR doesnot exist $N"
   exit 1
fi   


if [ ! -d $DEST_DIR ]; then
   echo -e "$R destination $DEST_DIR doesnot exist $N"
   exit 1
fi   

#find the file
FILES=$(find "$SOURCE_DIR" -name "*.log" -type f -mtime +"$DAYS")

if [ -n "$FILES" ]; then
#start archiving
    echo "Files found:"
    echo "$FILES"
    TIMESTAMP=$(date +%F-%H-%M-%S)
    ZIP_FILE_NAME="$DEST_DIR/app-logs-$TIMESTAMP.zip"
    echo "Zip file name: $ZIP_FILE_NAME"
    find "$SOURCE_DIR" -name "*.log" -type f -mtime +"$DAYS" | zip -@ -j "$ZIP_FILE_NAME"
     
     #chech archival success ot not
     if [ -f $ZIP_FILE_NAME ]
     then
         echo -e "ARCHIVAL....$G SUCCESS $N"
         while IFS= read -r filepath

  #delete if success
do
   echo "Deleting the file: $filepath"
   rm -rf "$filepath"
   echo "deleted the file: $filepath"
done <<< "$FILES"
     else
        echo "ARCHIVAL....$R FAILURE $N"
         exit 1

else
    echo -e "$Y No files to archive... SKIPPING $N"
fi