#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-4}  #if not provided considered as 14 days

LOGS_FOLDER="/var/log/shell-script"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log" # /var/log/shell-script/16-logs.log

mkdir -p $LOGS_FOLDER
echo "Script started executed at: $(date)" | tee -a $LOG_FILE

if [ $USERID -ne 0 ]; then
    echo "ERROR:: Please run this script with root privelege"
    exit 1 # failure is other than 0
fi


USAGE(){
    echo -e "$R USAGE: sudo sh backup.sh <SOURCE.DIR> <DEST.DIR> <DAYS>[optional] , default 14 days] $N"
    exit 1
}


if [ $# -lt 2 ]; then
   USAGE
fi


if [ ! -d $SOURCE_DIR ]; then
   echo -e "$R source $SOURCE_DIR doesnot exist $N"
   exit 1
fi   


if [ ! -d $DEST_DIR ]; then
   echo -e "$R destination $DEST_DIR doesnot exist $N"
   exit 1
fi   

FILES=$(find $SOURCE_DIR -name "*log" -type f -mtime +14 +"$DAYS")

if [ ! -n "$FILES" ]; then
    echo "files found: $FILES"
    TIMESTAMP=$(date +%F-%H-%M-%S)
    ZIP_FILE_NAME="$DEST_DIR/app-logs-$TIMESTAMP.zip"
    echo "Zip file name: $ZIP_FILE_NAME"
    echo $FILES | zip -@ -j "$ZIP_FILE_NAME"
else
    echo -e "no files to archive .... $Y SKIPPING $N"
fi   